### ISSUE TITLE
Fix tests for v2

### ISSUE THREAD

**Issue by mgred** [rapidjs/rapid.js#46]
This issue is for fixing all tests

`npm run unit`

**Comment by mgred** [comment]
Executed `jest` on the branch `mgred:rapid.js-41`:
![tty](https://user-images.githubusercontent.com/2325260/40365750-a40161fe-5dd5-11e8-829c-e858809df100.gif)

**Comment by drewjbartlett** [comment]
@mgred thanks a ton for this! Have you pushed this into the branch? I started a refactor last night in another branch that will keep all tests green as I work. Here's my tentative plan for the moment: 

- Get things refactored while being assured tests are all green
- Simplify rapid to exactly where I want it in vanilla js
- All the while add `// @ts-check` in the heading of the file to loosely ts check the files
- Make a PR into the the v2 branch with the refactor and we can go from there. I should've had the tests green the entire time rather than rewriting and now trying to clean it up.

Let's hang tight for a week or so and then we can actually get this bad boy rollin'! I seriously appreciate all your help!
